name: GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    environment: deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        persist-credentials: false
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - name: Install
      run: npm ci
    - name: Build and Deploy
      env:
        NODE_ENV: deploy
        # This is set automatically by github
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config user.name "Automated"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/arthurchevalley/personal-site.git
          npm run deploy
